# Generated by Django 4.0 on 2021-12-15 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Membership', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='subscription_type',
            field=models.ForeignKey(default='free', on_delete=django.db.models.deletion.CASCADE, to='Membership.subscriptiontype'),
        ),
    ]
