# Generated by Django 4.0 on 2021-12-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Membership', '0006_membership_subscription_remove_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='sub_type',
            field=models.CharField(choices=[('Premium', 'Premium'), ('Free', 'Free')], default='Free', max_length=30),
        ),
    ]
