# Generated by Django 4.0 on 2021-12-15 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Membership', '0007_alter_membership_sub_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='sub_type',
            new_name='membership_type',
        ),
    ]
